os:
    - linux
language: python
python:
    - "3.4"
install:
    - pip install coverage
    - python -m omelet.docker.travis_install
script: nosetests --verbosity=3 -x --with-coverage --cover-package=omelet
services: 
    - docker
before_script:
    - docker ps 
env:
    - SYN_DOCKER=1
