os:
    - linux
language: python
python:
    - "3.4"
install:
    - python -m omelet.docker.build
script: nosetests --verbosity=3 -x --with-coverage --cover-package=omelet
services: 
    - docker
before_script:
    - docker ps | grep -q core_ram
env:
    - SYN_DOCKER=1
